### ISSUE TITLE
send by pressing Enter

### ISSUE THREAD

**Issue by AnotherKamila** [AnotherKamila/stalky#8]
Add an "on Enter key" event to the data input field, so that pressing Enter sends data. Right now one has to press Tab then Enter (to focus and use the Send button), which is annoying.

**Comment by JolandaNava** [comment]
This project looks super interesting - I am looking forward to see how it integrates with different hardware and different apps (I saw you have plans for Clue!). In the spirit of hacktoberfest I had a try at solving your `onEnter` issue :)

By the way, the build instructions aren't super intuitive - so if you have some time a more detailed step-by-step might be helpful. And if you plan to keep working on this for a while, consider opening an issue for moving to Elm 0.19 - though it would require quite the rewriting since you're using the `mld` package.

**Comment by AnotherKamila** [comment]
Hi, I'm glad you find this interesting, and thanks a lot for the PR! I do intend to develop this further, but right now I have a lot of other stuff going on, so I am not able to work on it at the moment. Thanks for your input, I'll be sure to come back to it once I have time again.

Keep hacking! :-)
